### ISSUE TITLE
Compute config error

### ISSUE THREAD

**Issue by kristiandrucker** [reachsrirams/openstack-install-scripts#6]
While running this `bash configure.sh xxx.xxx.xxx.xxx` on my node it stuck at the end of the code calling a file with ip missing. `bash $dir_path/lib/configure-packages.sh $node_type` No ip after node type please may you fix it?

**Comment by reachsrirams** [comment]
Hi kristiandrucker

Thanks a lot for catching this. Fix is ready and I am testing it.

Sriram

**Comment by kristiandrucker** [comment]
You welcome

**Comment by reachsrirams** [comment]
I have tested the fix and things seem to be working fine. The fix is available on the latest master as well as stable-mitaka branch.
